apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-service-staging
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: greeter-service
      environment: staging
  template:
    metadata:
      labels:
        app: greeter-service
        environment: staging
    spec:
      containers:
        - image: dddomin3/greeter-server@sha256:79902cdb29fde54319d542b301d30c3e165811e64faa2376e80fdc62b1b3d9bc
          imagePullPolicy: IfNotPresent
          name: greeter-server
          ports:
            - containerPort: 5000
